---
name: 🧪 Test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*
      - src/**
      - test/**

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    if: github.actor != 'renovate[bot]'

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v6

      - uses: pre-commit/action@v3.0.1

  tests:
    name: 🧪 Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v6

      - name: 🕶 Install uv
        uses: astral-sh/setup-uv@v5

      - name: 🧪 Run tests with coverage
        run: |
          uv sync --group dev
          uv run coverage run -m pytest --exitfirst
          uv run coverage report --show-missing
